lang: ta-IN
google_site_verification: i3TSY3HYLI5mB30wmaoE13TDFRcQ7AU48Z1fc1mE-Jo
locale: ta_IN

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
collections:
  videos:
    output: true
    
defaults:
  -
    scope:
      path: ["**/*.json"]
    values:
      sitemap: false

